const tweets = [
  { project:"Zama", title:"Zama — Research / Content 01", url:"https://x.com/MaliBiswa/status/1996037628723167627", summary:"Zama-focused Web3 research turned into a concise social post. The final case study will pair the original post with the exact metrics and research context.", angle:"Research → simplify → publish", metrics:["Original X post","Zama","Analysis ready"] },
  { project:"Zama", title:"Zama — Research / Content 02", url:"https://x.com/MaliBiswa/status/1996482588756898139", summary:"A second Zama post showing how the ecosystem can be explored through a creator + researcher lens.", angle:"Ecosystem research → narrative", metrics:["Original X post","Zama","Analysis ready"] },
  { project:"Base", title:"Base — Ecosystem Post 01", url:"https://x.com/MaliBiswa/status/2047944101690212405", summary:"Base ecosystem content. This card is linked directly to the original X post so visitors can verify the work themselves.", angle:"Ecosystem → insight → attention", metrics:["Original X post","Base","Analysis ready"] },
  { project:"Base", title:"Base — Ecosystem Post 02", url:"https://x.com/MaliBiswa/status/2047166273361215975", summary:"Another Base-focused post, presented as part of the research and content archive.", angle:"Research → narrative → attention", metrics:["Original X post","Base","Analysis ready"] },
  { project:"Base", title:"Base — Ecosystem Post 03", url:"https://x.com/MaliBiswa/status/2039263683742945638", summary:"A third Base post documenting your exploration of the ecosystem.", angle:"Explore → understand → communicate", metrics:["Original X post","Base","Analysis ready"] },
  { project:"Gensyn", title:"Gensyn — Technical Post 01", url:"https://x.com/MaliBiswa/status/2048762782779408493", summary:"Gensyn content from a hands-on technical exploration perspective, connected to your node-runner experience.", angle:"Hands-on → learn → explain", metrics:["Original X post","Gensyn","Analysis ready"] },
  { project:"Gensyn", title:"Gensyn — Technical Post 02", url:"https://x.com/MaliBiswa/status/2047183902184497421", summary:"Gensyn research/content entry documenting the ecosystem from an explorer perspective.", angle:"Technical research → content", metrics:["Original X post","Gensyn","Analysis ready"] },
  { project:"Gensyn", title:"Gensyn — Technical Post 03", url:"https://x.com/MaliBiswa/status/2046913851216826404", summary:"Another Gensyn post added to the technical exploration archive.", angle:"Explore → test → communicate", metrics:["Original X post","Gensyn","Analysis ready"] },
  { project:"Polymarket", title:"Polymarket — Research Post 01", url:"https://x.com/MaliBiswa/status/2048347378621804802", summary:"Polymarket research and ecosystem exploration, linked directly to the source post.", angle:"Market research → narrative", metrics:["Original X post","Polymarket","Analysis ready"] },
  { project:"Polymarket", title:"Polymarket — Research Post 02", url:"https://x.com/MaliBiswa/status/2051568530622145022", summary:"A second Polymarket content entry for the research archive.", angle:"Research → context → attention", metrics:["Original X post","Polymarket","Analysis ready"] },
  { project:"Polymarket", title:"Polymarket — Research Post 03", url:"https://x.com/MaliBiswa/status/2050072184765522186", summary:"A third Polymarket post showing your continued exploration of prediction-market narratives.", angle:"Explore → understand → publish", metrics:["Original X post","Polymarket","Analysis ready"] }
];
